//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MedicalEntities : DbContext
    {
        public MedicalEntities()
            : base("name=MedicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int insertData(Nullable<double> platelets, Nullable<double> albumin)
        {
            var plateletsParameter = platelets.HasValue ?
                new ObjectParameter("platelets", platelets) :
                new ObjectParameter("platelets", typeof(double));
    
            var albuminParameter = albumin.HasValue ?
                new ObjectParameter("albumin", albumin) :
                new ObjectParameter("albumin", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertData", plateletsParameter, albuminParameter);
        }
    
        public virtual ObjectResult<P_getTable_Result> P_getTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_getTable_Result>("P_getTable");
        }
    }
}
